import { PrologueNft, Loan } from "@/types/nft";

const prologueNfts: PrologueNft[] = [
  {
    featured: true,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: true,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: true,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
  {
    featured: false,
    apy: 25,
    rank: 12,
    tvl: 30,
    icon: "/assets/images/nft.png",
  },
];

export const loans: Loan[] = [
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan1.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan2.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan3.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan1.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan2.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan3.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan1.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan2.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan3.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan1.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan2.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan3.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan1.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan2.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan3.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan1.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan2.svg",
  },
  {
    name: "Squiggles #3664",
    principal: 2,
    repay: 2,
    ltv: 80,
    apy: 15,
    due: 5,
    icon: "/assets/images/vaultIcon.svg",
    market: "/assets/icons/loan3.svg",
  },
];

export default prologueNfts;
